---
- name: Add Nodesource repositories for Node.js.
  yum:
    name: "https://rpm.nodesource.com/pub/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
    state: present

- name: Ensure Node.js and npm are installed.
  yum: "name=nodejs state=present enablerepo='epel,nodesource'"
