---

- name: Install php tools (via composer)
  shell:
    composer global require {{item}}
  with_items:
    - phpunit/phpunit:3.7.*
    - phing/phing:dev-master
    - zerkalica/phpcs:dev-master
    - fabpot/php-cs-fixer:0.4.*@dev
    - sebastian/phpdcd:1.0.*@dev
    - sebastian/phpcpd:2.0.*@dev
    - phploc/phploc:2.0.*@dev
    - phpmd/phpmd:*
    - squizlabs/php_codesniffer:1.*
    - pdepend/pdepend:dev-master
    - covex-nn/phpcb:1.0.*@dev
    - theseer/fxsl:1.0.*@dev
    - theseer/phpdox:0.6.0
    - behat/behat:3.0.*@dev
  tags: php-tools

- name: Install php tools (via nodejs)
  npm: name={{item}} global=yes
  with_items:
    - uglify-js
    - uglifycss
    - less
    - jshint
  tags: php-tools
