---

- name: Install Shorewall
  action: apt pkg={{item}} state=latest update-cache=yes
  with_items:
    - shorewall

- name: "template zones"
  action: template src=zones.j2 dest=/etc/shorewall/zones owner=root group=root mode=0644 backup=yes
  notify: Restart service shorewall

- name: "template interfaces"
  action: template src=interfaces.j2 dest=/etc/shorewall/interfaces owner=root group=root mode=0644 backup=yes
  notify: Restart service shorewall

- name: "template policy"
  action: template src=policy.j2 dest=/etc/shorewall/policy owner=root group=root mode=0644 backup=yes
  notify: Restart service shorewall

- name: "template rules"
  action: template src=rules.j2 dest=/etc/shorewall/rules owner=root group=root mode=0644 backup=yes
  notify: Restart service shorewall

- name: "template masq"
  action: template src=masq.j2 dest=/etc/shorewall/masq owner=root group=root mode=0644 backup=yes
  notify: Restart service shorewall

- name: "Enable shorewall service"
  action: lineinfile dest=/etc/default/shorewall regexp=^startup= line=startup=1
  notify: Restart service shorewall
